name: CI - Main

on:
  push:
    branches: 
      - 'main'

jobs:
  
  release:
    name: Create stable release
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_ORG: devopskf
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version (minor) and create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor

      - name: Create a GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          prerelease: false

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build Docker image
        run: docker build . --tag ${{ env.DOCKERHUB_ORG }}/${{ github.event.repository.name }}:${{ steps.tag_version.outputs.new_tag }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.DOCKERHUB_ORG }}/${{ github.event.repository.name }}:${{ steps.tag_version.outputs.new_tag }}